name = input("Enter Your Name: ")
age = int(input("Enter Your age: "))
education = input("Enter Your education: ")
print(name)
print(age)
print(education)
print(type(name))
print(type(age))
print(type(education))